require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'
#use_modular_headers!
# use_frameworks!

target 'AwesomeWeb3Example' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  pod 'react-native-awesome-web3', :path => '../..'
   pod 'OpenSSL', :git => 'https://github.com/bither/OpenSSL.git', :branch => 'master'
   pod 'Bitheri', :git => 'https://github.com/bither/bitheri.git', :branch => 'develop'
  
#  pod 'web3swift', '~> 2.3.0'
#  pod 'web3swift', '~> 2.3.0', :modular_headers => true

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({'Flipper' => '0.92.0', 'Flipper-Folly' => '2.6.7'})
  
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      end
    end 
  end
end
